### ISSUE TITLE
please remove max-button-length limit

### ISSUE THREAD

**Issue by ecc1** [trustable-code/Xfce-Simple-Dark#1]
The limit of 130 pixels on line 161 of gtk-2.0/gtkrc seems arbitrary, and is much too small for me on a large monitor, with many long window titles (like browsers).

I suggest you remove it entirely. Those who want to reduce the size can put fixed-width spacers elsewhere in the panel to constrain the window buttons.

Thanks for this theme, it's one of the few dark modes I've found that work well.

**Comment by simonkrauter** [comment]
Hi, thanks for your feedback :-)

I have removed the gtk-2.0 XfceTasklist::max-button-length.  (commit cd39002df3da69abc37f233e8c725d65191f454a)
On my main desktop it doesn't make a difference, so I'm fine with it.
