### ISSUE TITLE
Update readme.me to add AUR Package installation method

### ISSUE THREAD

**Issue by Intestinall** [trustable-code/Xfce-Simple-Dark#2]
In order to facilitate the installation of your package on Archlinux, I created an [AUR package](https://aur.archlinux.org/packages/xfce-simple-dark/).
You may want to updated your `readme.md` to add this installation method.
Of course, you can check the installation script I made and I can make you Co-Maintainers of the AUR package.

**Comment by simonkrauter** [comment]
Oh, nice!
